version: 2
jobs:
  build:
    working_directory: ~/DevopsTestBP
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            echo 'export TAG=1.0' >> $BASH_ENV
            echo 'export IMAGE_NAME=devops-image' >> $BASH_ENV 
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run "python manage.py test"
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=gcloud-key-file.json
            gcloud --quiet config set project devops-242622
            gcloud --quiet config set compute/zone asia-east1
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
