version: 2
jobs:
  build:
    working_directory: ~/DevopsTestBP
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run "python manage.py test"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  deploy:
    working_directory: ~/DevopsTestBP
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          working_directory: /home/DevopsTestBP
          command: |
            pwd
#            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
#            gcloud --quiet config set project devops-242622
#            gcloud --quiet config set compute/zone asia-east1
#            gcloud -q app deploy deploy.sh
workflows:
  version: 2
  build/deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

